sudo: required
language: php
services:
  - docker
before_install:
  - docker build -t gpgl/test-core ./tests
install:
  - docker run --rm -it -v "$PWD":/code gpgl/test-core composer install
script:
  - docker run --rm -it -v "$PWD":/code gpgl/test-core ./vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
